server:
  port: 8088

spring:

  datasource:
    url: jdbc:mysql://101.201.235.107:3306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://101.201.235.107:27017
      database: test

  redis:
    port: 6379
    host: 101.201.235.107
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        timeout: 10000


mybatis-plus:
  mapper-locations: classpath*:com/mall/mbg/mapper/*.xml
  type-aliases-package: com.mall.mbg.pojo

elasticsearch:
  ip: 101.201.235.107:9200

